version: "3"

services:
  app:
    image: issuelist.azurecr.io/issuelistapp:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    volumes:
      - ./:/go/src
    command: go run main.go
    ports:
      - 1323:1323
