# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - issueList-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://issuelist.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5cd7cb8d749c4017984a8cd4b4d4c547 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e98cfb6addb45f38e546b963479404d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: issuelist.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5cd7cb8d749c4017984a8cd4b4d4c547 }}/issuelistapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'issueList-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e89e0f5e44e24395b2b8f33e742bbdc6 }}
        images: 'issuelist.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5cd7cb8d749c4017984a8cd4b4d4c547 }}/issuelistapp:${{ github.sha }}'